l=138e-3;
theta1=pi/4;
SP.psi.theta1=theta1;
SP.psi.l=l;
SP.psi.phi=4.1108;
SP.psi.delta1=0;
SP.psi.theta2=pi/2-theta1;
SP.psi.delta2=0;

SP=setInitValV2(SP);
L1=SP.structure.L1;
c=SP.trocar.c;
OP=setOP;
pre_d=10e-3;
r_zero_pose=getZeroPose(theta1);
flag_k=1;
if(r_zero_pose>c/2)
        i=0;
while(i<20)
    if(l>SP.structure.L1+SP.structure.L2+SP.structure.Lr)
        [xh,yh,exitflag_1]=fmincon('costFunc_1',OP.x1,[],[],[],[],OP.xhmin1,OP.xhmax1,'nonlcon_1',OP.options);
        OP.x1=rand(1,max(size(OP.xhmax1))).*(OP.xhmin1-OP.xhmax1)+OP.xhmax1;
        flag_k=1;
    else
        [xh,yh,exitflag_1]=fmincon('costFunc_2',OP.x2,[],[],[],[],OP.xhmin2,OP.xhmax2,'nonlcon_2',OP.options);
        OP.x2=rand(1,max(size(OP.xhmax2))).*(OP.xhmin2-OP.xhmax2)+OP.xhmax2;
        flag_k=2;
        if(xh(1)/50+xh(2)/10>L1)
            [xh,yh,exitflag_1]=fmincon('costFunc_3',OP.x3,[],[],[],[],OP.xhmin3,OP.xhmax3,'nonlcon_3',OP.options);
            OP.x3=rand(1,max(size(OP.xhmax3))).*(OP.xhmin3-OP.xhmax3)+OP.xhmax3;
            flag_k=3;
        end
    end
    i=i+1;
    if(exitflag_1==1)
        break;
    end
end

    Tc=plotResult(1,flag_k,"");
else
    Tc=plotResult(1,"",flag_k);
end
Tn=plotResult_noClearance(1,flag_k,0);

