#pragma once
#include <Eigen/Core>

struct Kmp {
    Eigen::Vector3d PO_sb;
    Eigen::Matrix3d RO_sb;
    Eigen::Vector3d Psb_1b;
    Eigen::Matrix3d Rsb_1b;
    Eigen::Vector3d P1b_1e;
    Eigen::Matrix3d R1b_1e;
    Eigen::Vector3d P1e_2b;
    Eigen::Matrix3d R1e_2b;
    Eigen::Vector3d P2b_2e;
    Eigen::Matrix3d R2b_2e;
    Eigen::Vector3d P2e_g;
    Eigen::Matrix3d R2e_g;
    Eigen::Vector3d Psb_g_in_sb;
    Eigen::Vector3d P1e_g_in_sb;
    Eigen::Vector3d P2e_g_in_2b;
    Eigen::Vector3d PO_g;
    Eigen::Matrix3d RO_g;
};

struct MP {
    MP();
    MP resetMP(Eigen::VectorXd);
    Eigen::VectorXd getMP();
    Eigen::Matrix3d S(const Eigen::Vector3d& p);
    Eigen::Vector3d e1;
    Eigen::Vector3d e2;
    Eigen::Vector3d e3;
    double E;
    double mu;
    double d1;
    double d2;
    double d3;
    double rho1;
    double rho2;
    double rhop;
    double rho3;
    double alpha;
    double L1;
    double L2;
    double L3;
    double Lc;
    double La;
    double Lr;
    double Lg;
    Eigen::Vector3d r11;
    Eigen::Vector3d r12;
    Eigen::Vector3d r13;
    Eigen::Vector3d r14;
    Eigen::Vector3d r21;
    Eigen::Vector3d r22;
    Eigen::Vector3d r23;
    Eigen::Vector3d r24;
    Eigen::Vector3d r25;
    Eigen::Vector3d r26;
    Eigen::Vector3d r27;
    Eigen::Vector3d r28;
    Eigen::Vector3d r29;
    Eigen::Vector3d r2a;
    Eigen::Vector3d r2b;
    Eigen::Vector3d r2c;
    Eigen::Vector3d r2d;
    Eigen::Vector3d r2e;
    Eigen::Vector3d r2f;
    Eigen::Vector3d r2g;
    Eigen::Vector3d r31;
    Eigen::Vector3d r32;
    Eigen::Vector3d r33;
    Eigen::Vector3d r34;
    Eigen::Matrix3d Q1;
    Eigen::Matrix3d Q2;
    Eigen::Matrix3d Q3;
    double I1;
    double A1;
    double I2;
    double A2;
    double I3;
    double A3;
    double G;
    double J1;
    double J2;
    double J3;
    Eigen::Matrix3d Ke1;
    Eigen::Matrix3d Ke2;
    Eigen::Matrix3d Ke3;
    Eigen::Matrix3d Kb1;
    Eigen::Matrix3d Kb2;
    Eigen::Matrix3d Kb3;
    double zeta;
    double L1x;
    double d;

};